#!/bin/bash
set -e

TOP=$(cd $(dirname $0)/../../.. && pwd)

function cleanup {
  # Kokoro will rsync back everything created by the build. Since we don't care
  # about any artifacts on this build, nuke EVERYTHING at the end of the build.
  rm -rf "${TOP}"/*
}
trap cleanup EXIT

cd $TOP

# Apply local patches
for filename in toolchain/llvm_android/kokoro/tot-patches/*.patch; do
  [ -e "$filename" ] || continue
  patch -p1 < ${filename}
done

# Create symlinks necessary to build Android.
# They are generated by repo, but we are using explicit SCM and it does not
# create them for us.
for f in CleanSpec.mk buildspec.mk.default core envsetup.sh target tools; do
  ln -sf make/$f build/$f
done

mkdir dist
DIST_DIR=dist \
OUT_DIR=out \
prebuilts/python/linux-x86/bin/python3 \
  toolchain/llvm_android/test_compiler.py --build-only \
  --target ${AOSP_BUILD_TARGET}-aosp_current-userdebug \
  --module sync \
  --clang-package-path ${KOKORO_GFILE_DIR} .

